Drink_Buddy/Drink_Buddy/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from drink_service import views
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views
from rest_framework import routers
from Educational.api_views import EducationalViewSet, EducationalListAPIView, EducationalDetailAPIView, EducationalCreateAPIView, EducationalUpdateAPIView,EducationalDeleteAPIView

router = routers.DefaultRouter()
router.register('edu',EducationalViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("register/", user_views.register, name='register'),
    path("profile/", user_views.profile, name='profile'),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path("landing/", views.landing_page, name='landing_page'),
    path('response/', views.response_page, name= 'response_page'),
    path('premium/', views.premium, name= 'premium'),
    path("", include('drink_service.urls', namespace='drink_service')),
    path("", include('blog.urls', namespace='blog')),
    path('Educational/', include('Educational.urls', namespace='Educational')),
    path('edu_list/', include(router.urls)),
    path('api/v1/', EducationalListAPIView.as_view(), name='api-list-educational'),
    path('api/v1/create', EducationalCreateAPIView.as_view(), name='api-create-educational'),
    path('api/v1/<int:pk>', EducationalDetailAPIView.as_view(), name='api-detail-educational'),
    path('api/v1/update/<int:pk>', EducationalUpdateAPIView.as_view(), name='api-update-educational'),
    path('api/v1/delete/<int:pk>', EducationalDeleteAPIView.as_view(), name='api-delete-educational'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Drink_Buddy/Educational/urls.py
from django.urls import path
from . import views

app_name = 'Educational'


urlpatterns = [
    path('', views.all_educational, name='all_educational'),
    path('<int:Insight_id>/', views.detail, name='detail'),
    
]

Drink_Buddy/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views
from .views import PostListAPIView

app_name = 'blog'

urlpatterns = [
    path('post/', PostListView.as_view(), name='post-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/api/', PostListAPIView.as_view(), name='post-api_list'),

    
]

Drink_Buddy/drink_service/urls.py
from django.urls import path
from . import views

app_name = 'drink_service'

urlpatterns = [
    path('drinks/', views.drinks, name= 'drinks'),
    path("recipe_detail/<int:id>/", views.recipe_detail, name='drink_service-detail'),
    path('search/',views.search_drinks, name='search_drinks'),
]

Drink_Buddy/drink_service/models.py
from django.db import models

class UserLocation(models.Model):
    location = models.CharField(max_length=100)

class Drinks(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='Drink/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title
             
class Drink(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.TextField()
    recipe = models.TextField()
    timeofyear = models.CharField(max_length=100)
    timetodrink = models.CharField(max_length=100)
    socialsituation = models.CharField(max_length=100)
    mood = models.CharField(max_length=100)
    iscoffee = models.BooleanField(default=False)
    istea = models.BooleanField(default=False)
    isalcoholic = models.BooleanField(default=False)
    isnonalcoholic = models.BooleanField(default=False)
    imagefile = models.ImageField(upload_to='images/recipes', blank= True, null=True)
    temperatureoflocation = models.CharField(max_length=100)
    timeofday = models.CharField(max_length=100)

Drink_Buddy/drink_service/views.py
from django.shortcuts import render, redirect
from .models import Drinks, UserLocation, Drink
from django.db import IntegrityError
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
import requests
from decouple import config
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.core.paginator import Paginator


def home(request):
    Drink = Drinks.objects.all()
    return render(request, 'drink_service/home.html', {'Drink': Drink})
        
@login_required
def logoutuser(request):
    if request.method == 'POST': #make it quick
        logout(request)
        return redirect('home')

def landing_page(request):
    if request.method == 'POST':
        location = request.POST.get('location')
        UserLocation.objects.create(location=location)
        return redirect('response_page')
    return render(request, 'drink_service/landing_page.html')

def response_page(request):
    user_location = UserLocation.objects.latest('id')
    location = user_location.location
    api_key = config('WEATHER_API_KEY')
    url = f'http://api.weatherapi.com/v1/current.json?key={api_key}&q={location}&aqi=no'
    response = requests.get(url)
    
    try:
        #response.status_code==200
        # Make API call to retrieve weather information
         
        weather_data = get_weather_data(location)
        # Extract required weather data
        temperature = weather_data['current']['temp_c']
        description = weather_data['current']['condition']['text']
        time_data = weather_data['location']['localtime']
        icon_weather = weather_data['current']['condition']['icon']
        icon_link = 'https://' + icon_weather
        # Make API call to retrieve local time information
        local_time = time_data.split()[1]  # Extract time from datetime string
        # Extract local hour
        local_hour = int(local_time.split(':')[0])
        #local_hour = int(local_time[:1])
        
        # Extract required weather data
        temperature = weather_data['current']['temp_c']
    
        # Get matching recipes from the database
        recipes = get_matching_recipes(temperature, local_hour)
    except:
        return render(request, 'drink_service/home.html',{'error': 'Invalid Location name'})
      
    context = {
        'location': location,
        'temperature': temperature,
        'description': description,
        'local_time': local_time, 
        'local_hour': local_hour,
        #'icon': icon_weather,
        'recipes': recipes,
        'icon_link': icon_link
    }
        
    return render(request, 'drink_service/response_page.html', context)

def get_weather_data(location):
    # Make an API call to retrieve weather information based on the location
    # Replace 'API_KEY' with your actual API key
    api_key = config('WEATHER_API_KEY')
    url = f'http://api.weatherapi.com/v1/current.json?key={api_key}&q={location}&aqi=no'
    response = requests.get(url)
    weather_data = response.json()
    return weather_data

def get_local_time_data(location):
    # Make an API call to retrieve local time information based on the location
    # Replace 'API_KEY' with your actual API key
    api_key = 'API_KEY'
    url = f'https://worldtimeapi.org/api/timezone/{location}'
    response = requests.get(url)
    time_data = response.json()
    return time_data


def get_matching_recipes(temperature, local_hour):
    # Get matching recipes from the database based on temperature and local time ranges
    if local_hour >= 5 and local_hour <= 11:
        time_range = "5 to 11"
    elif local_hour >= 12 and local_hour <= 23:
        time_range = "12 to 23"
    else:
        return []

    if temperature >= -15 and temperature < 0:
        temperature_range = "-15 to 0"
    elif temperature >= 0 and temperature < 10:
        temperature_range = "0 to 10"
    elif temperature >= 10 and temperature < 20:
        temperature_range = "10 to 20"
    else:
        temperature_range = "20+"

 # Get matching recipes based on time and temperature ranges
    recipes = Drink.objects.filter(timeofday=time_range, temperatureoflocation=temperature_range)[:3]
    return recipes


def premium(request):
    return render(request, 'drink_service/premium.html')


def recipe_detail(request, id):
    recipe = Drink.objects.get(id=id)
    return render(request, 'drink_service/recipe_detail.html', context={"recipe": recipe})


def drinks(request):
    context = {
        'recipes': Drink.objects.all(),  
    }
    return render(request, 'drink_service/drinks.html', context)

def search_drinks(request):
    if request.method == 'GET':
        # Get the search parameters from the request
        name = request.GET.get('name')
        ingredients = request.GET.get('ingredients')
        temperature = request.GET.get('temperature')
        time_of_day = request.GET.get('time_of_day')
        time_of_year = request.GET.get('time_of_year')
        social_situation = request.GET.get('social_situation')
        mood = request.GET.get('mood')

        # Filter the drinks based on the search parameters
        recipes = Drink.objects.all()

        if name:
            recipes = recipes.filter(name__icontains=name)

        if ingredients:
            recipes = recipes.filter(ingredients__icontains=ingredients)

        if temperature:
            recipes = recipes.filter(temperatureoflocation=temperature)

        if time_of_day:
            recipes = recipes.filter(timeofday=time_of_day)

        if time_of_year:
            recipes = recipes.filter(timeofyear__icontains=time_of_year)

        if social_situation:
            recipes = recipes.filter(socialsituation__icontains=social_situation)

        if mood:
            recipes = recipes.filter(mood__icontains=mood)

        paginator = Paginator(recipes, 10)

        page_number = request.GET.get('page')
        recipes = paginator.get_page(page_number)
        return render(request, 'drink_service/search.html', {'recipes': recipes})

    return render(request, 'drink_service/search.html')

Drink_Buddy/drink_service/templates/drink_service/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'drink_service/custom.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/jpg" href="{% static 'drink_service/drink.jpg' %}">
    <title>Drink Buddy</title>
  </head>
  <body>
  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'drink_service/drink.jpg' %}" width="40" height="40" class="d-inline-block align-top" alt="Drink_Buddy's Logo">
        <span>Drink Buddy</span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'landing_page' %}">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>  
          
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

Drink_Buddy/drink_service/templates/drink_service/drinks.html
{% extends "drink_service/premium_base.html" %}
{% load static %}
{% block content %}
<br>
<br>
<div class="username">
    <br>
    <h1>All Recipes</h1>
    <br>
    <h2>
    {% if user.is_authenticated %}
    Hi {{ user.username }}, welcome to Drink Buddy Premium!
    {% endif %}
    </h2>
    <h2>Click any drink you like and see it's recipes</h2>
</div>
<br>
<br>
<div class="row">
    {% for recipe in recipes %}
    <div class="col">
        <div class="card">
            <a href="{% url 'drink_service:drink_service-detail' recipe.id %}">
            <img src="{{ recipe.imagefile.url }}" class="card-img-top"></a>
            <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

Drink_Buddy/drink_service/templates/drink_service/home.html
{% extends 'drink_service/base.html' %}
{% load static %}
{% block content %}

<br>
<br>
<!-- <h1>Welcome to Drink Buddy App! </h1> -->
<br>
<!-- <p>This app will suggest you Drinks,Coffee,Tea according to weather. </p> -->
<br>
<br>
<div class="location_info">
    <p class="text_field">
        Welcome to Drink Buddy! We believe that the right drink can complement both the weather and the time of day. From refreshing iced beverages on sunny afternoons to cozy warm drinks for chilly evenings, our app will curate personalized drink recommendations to enhance your every moment. Discover the perfect blend of flavors that aligns with the current weather and time, ensuring a delightful and satisfying beverage experience.
    </p>
    <form method="post" action="{% url 'landing_page' %}">
    {% csrf_token %}
    {{ error }}
    <br><br>
    <label for="location">Enter your location:</label>
    <input type="text" name="location" id="location" required class="input-style">
    <button class = 'buttons' type="submit">Submit</button>
    </form>
</div>

{% endblock %}

Drink_Buddy/drink_service/templates/drink_service/premium.html
{% extends 'drink_service/premium_base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="username">
    <h1>
    {% if user.is_authenticated %}
    Hi {{ user.username }}, welcome to Drink Buddy Premium!
    {% endif %}
    </h1>
</div>

<div class="text_field">
    <p>Unlock a world of exquisite flavors and endless possibilities with our Premium page, gaining exclusive access to curated drink options, ranging from rare spirits to artisanal cocktails. Elevate your knowledge as a connoisseur through our educational section, delving into fascinating facts and historical anecdotes from the captivating world of drinks. Experience the epitome of luxury with personalized recommendations, early access to limited editions, and preferential pricing as a Premium member.</p>
    <p>Immerse yourself in a community of like-minded enthusiasts, connecting through interactive forums, live tastings, and valuable insights. Access a treasure trove of hidden gems, showcasing rare, boutique, and hard-to-find beverages, ensuring an extraordinary taste experience that keeps you one step ahead.</p>
</div>

<div class="buttons">
<a class="nav-link" href="{% url 'drink_service:drinks' %}"><h5>Click here to see more suggestions</h5></a>
</div>

{% endblock %}

Drink_Buddy/drink_service/templates/drink_service/premium_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'drink_service/custom_premium.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="icon" type="image/jpg" href="{% static 'drink_service/drink.jpg' %}">
    
    <title>Drink Buddy</title>
  </head>

  <body>  
  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'premium' %}">
        <img src="{% static 'drink_service/drink.jpg' %}" width="40" height="40" class="d-inline-block align-top" alt="Drink_Buddy's Logo">

        <span>Drink Buddy</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <div class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'drink_service:search_drinks' %}">Search</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post-home' %}">Blog</a>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'drink_service:drinks' %}">Drinks</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'Educational:all_educational' %}">Educational</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Log-out</a>
          </li>  
        </ul>
      </div>
    </div>
    {% if user.is_authenticated %}
    {{ user.username }}
    {% endif %}
  </nav>
<div class="container">
  {% block content %}{% endblock %}
</div>
  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

Drink_Buddy/drink_service/templates/drink_service/premium_drink_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'drink_service/custom_premium.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="icon" type="image/jpg" href="{% static 'drink_service/drink.jpg' %}">
    <title>Drink Buddy</title>
  </head>
    <header>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'premium' %}">
          <img src="{% static 'drink_service/drink.jpg' %}" width="40" height="40" class="d-inline-block align-top" alt="Drink_Buddy's Logo">
  
          <span>Drink Buddy</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'landing_page' %}">About us</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'drinks' %}">Drinks</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post-home' %}">Blog</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Educational:all_educational' %}">Educational</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Sign-out</a>
            </li>        
          </ul>
        </div>
      </div>
    </nav>
    </header>
  
  <body>  
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
<<<<<<< HEAD

</html>
=======
  
</html>
>>>>>>> Raman

Drink_Buddy/drink_service/templates/drink_service/recipe_detail.html
{% extends "drink_service/premium_base.html" %}
{% load static %}
{% block content %}
    <title>Recipe Detail</title>
    <link rel="stylesheet" href="{% static 'drink_service/custom_premium.css' %}">
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <header>
        <h1>{{ recipe.name }}</h1>
    </header>
    <main class="trial">
        <div class="result_image">
            <img src="{{ recipe.imagefile.url }}" class="card-img-top">
        </div>
        <div class="text_field">
            <h4>{{ recipe.title }}</h4>
            <p>{{ recipe.description }}</p>
            <h4>Ingredients</h4>
            {{ recipe.ingredients }}
            <h4>Recipe</h4>
            {{ recipe.recipe }}
        </div>           
    </main>
</body>
    <footer>
        <br>
        <br>
        <p>Drink Buddy &copy; 2023</p>
    </footer>
{% endblock content %}

Drink_Buddy/drink_service/templates/drink_service/search.html
{% extends 'drink_service/premium_base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="username">
    <h1>
    {% if user.is_authenticated %}
    Hi {{ user.username }}, let's search for some drinks!
    {% endif %}
    </h1>
</div>
<div>
    <br><br>
    <form method="GET" action="{% url 'drink_service:search_drinks' %}">
        <input type="text" name="name" placeholder="Drink Name"  class="input-style">
        <input type="text" name="ingredients" placeholder="Ingredients"  class="input-style">
        <br><br>
        <select name="temperature" class="input-style">
            <option value="">Temperature</option>
            <option value="20+">20+</option>
            <option value="10 to 20">10 to 20</option>
            <option value="0 to 10">0 to 10</option>
            <option value="-15 to 0">-15 to 0</option>
        </select>
        <select name="time_of_day" class="input-style">
            <option value="">Time of Day</option>
            <option value="5 to 11">5 to 11</option>
            <option value="12 to 23">12 to 23</option>
        </select>
        <br><br>
        <select name="time_of_year" class="input-style">
            <option value="">Time of Year</option>
            <option value="christmas">Christmas</option>
            <option value="summer">Summer</option>
            <option value="winter">Winter</option>
            <option value="all_year">All Year</option>
            <option value="fall">Fall</option>
            <option value="spring">Spring</option>
        </select>
    
        <select name="social_situation" class="input-style">
            <option value="">Social Situation</option>
            <option value="alone">Alone</option>
            <option value="wedding">In a Wedding</option>
            <option value="party">In a Party</option>
            <option value="friends">With Friends</option>
            <option value="park">On the Park</option>
            <option value="to_go">To Go</option>
            <option value="home">Relaxing at Home</option>
            <option value="breakfast">For Breakfast</option>
            <option value="brunch">Outdoor Brunch</option>
            <option value="cafe_chat">Cozy Café Chat</option>
            <option value="picnic">Picnic in the Park</option>
            <option value="outdoor_party">Outdoor Party</option>
            <option value="study_work">Studying or Working</option>
            <option value="beach">At the Beach</option>
            <option value="cozy_night">Cozy Night at Home</option>
            <option value="drink_night">Cozy Drink Night</option>
        </select>
        <br><br>
        <select name="mood" class="input-style">
            <option value="">Mood</option>
            <option value="cheerful">Cheerful</option>
            <option value="reflective">Reflective</option>
            <option value="romantic">Romantic</option>
            <option value="calm">Calm</option>
            <option value="cozy">Cozy</option>
            <option value="sociable">Sociable</option>
            <option value="hopeful">Hopeful</option>
            <option value="angry">Angry</option>
            <option value="tense">Tense</option>
            <option value="energetic">Energetic</option>
            <option value="refreshing">Refreshing</option>
        </select>
        
        <button class = 'buttons' type="submit">Search</button>
    </form>
    
    {% if recipes %}
        <div class="row">
            {% for recipe in recipes %}
                <div class="col">
                    <div class="card">
                        <a href="{% url 'drink_service:drink_service-detail' recipe.id %}">
                        <img src="{{ recipe.imagefile.url }}" class="card-img-top"></a>
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% else %}
        <p>No drinks found.</p>

    {% endif %}
    <br><br><br>

      <div class="container">
        <nav aria-label="Recipe Pagination">
          <ul class="pagination justify-content-center">
    
            {% if recipes.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ recipes.previous_page_number }}" aria-label="Previous">
                Previous
              </a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
            {% endif %}
    
            {% for i in recipes.paginator.page_range %}
              {% if recipes.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
              {% endif %}
            {% endfor %}
    
            {% if recipes.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ recipes.next_page_number }}" aria-label="Next">
                Next
              </a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
            {% endif %}
    
          </ul>
        </nav>
        <br><br>
      </div>
    
</div>
{% endblock %}