Drink_Buddy/Drink_Buddy/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from drink_service import views
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views
from rest_framework import routers
from Educational.api_views import EducationalViewSet, EducationalListAPIView, EducationalDetailAPIView, EducationalCreateAPIView, EducationalUpdateAPIView,EducationalDeleteAPIView

router = routers.DefaultRouter()
router.register('edu',EducationalViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("register/", user_views.register, name='register'),
    path("profile/", user_views.profile, name='profile'),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path("landing/", views.landing_page, name='landing_page'),
    path('response/', views.response_page, name= 'response_page'),
    path('premium/', views.premium, name= 'premium'),
    path("", include('drink_service.urls', namespace='drink_service')),
    path("", include('blog.urls', namespace='blog')),
    path('Educational/', include('Educational.urls', namespace='Educational')),
    path('edu_list/', include(router.urls)),
    path('api/v1/', EducationalListAPIView.as_view(), name='api-list-educational'),
    path('api/v1/create', EducationalCreateAPIView.as_view(), name='api-create-educational'),
    path('api/v1/<int:pk>', EducationalDetailAPIView.as_view(), name='api-detail-educational'),
    path('api/v1/update/<int:pk>', EducationalUpdateAPIView.as_view(), name='api-update-educational'),
    path('api/v1/delete/<int:pk>', EducationalDeleteAPIView.as_view(), name='api-delete-educational'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Drink_Buddy/Educational/urls.py
from django.urls import path
from . import views

app_name = 'Educational'


urlpatterns = [
    path('', views.all_educational, name='all_educational'),
    path('<int:Insight_id>/', views.detail, name='detail'),
    
]

Drink_Buddy/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views
from .views import PostListAPIView

app_name = 'blog'

urlpatterns = [
    path('post/', PostListView.as_view(), name='post-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/api/', PostListAPIView.as_view(), name='post-api_list'),

    
]

Drink_Buddy/Educational/models.py
from django.db import models


class Educational(models.Model):
    title= models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    
    
    def __str__(self):
        return self.title

Drink_Buddy/Educational/views.py
from django.shortcuts import render, get_object_or_404
from .models import Educational


def all_educational(request):
    Insights = Educational.objects.order_by('-date')
    return render(request, 'Educational/all_educational.html', {'Insights':Insights})


def detail(request, Insight_id):
    Insight = get_object_or_404(Educational, pk= Insight_id)
    return render(request, 'Educational/detail.html', {'Insight':Insight})

Drink_Buddy/Educational/templates/Educational/all_educational.html
{% extends 'drink_service/premium_base.html' %}
{% load static %}
{% block content %}

<br>
<div>
  <br>
  <br>
  <br>
  <h1 id="blogtitle" class="font-weight-bold text-center">Insights</h1>
  <h5 class="text-center mb-5">Drink Buddy has written {{ Insights.count }} Insight{{ Insights.count|pluralize }}</h5>
</div>

{% for Insight in Insights %}

  <div>
    <div>
      <br>
      <hr>
      <a href="{% url 'Educational:detail' Insight.id %}">
        <h4>{{ Insight.title }}</h4>
      </a>
      <h5 class="text-muted">{{ Insight.date|date:'M d Y'|upper }}</h5>
      <h4>{{ Insight.description|striptags|truncatechars:100 }}</h4>
    </div>
  </div>

{% endfor %}
{% endblock %}

Drink_Buddy/Educational/templates/Educational/detail.html
{% extends "drink_service/premium_base.html" %}
{% load static %}
{% block content %}

<br><br><br><br>

<div class="text_heading">
    <h3 class="text-center mt-5" id="blogdetailtitle">{{ Insight.title }}</h3>
    <h5 class="text-center text-muted mb-5">{{ Insight.date|date:'F jS Y' }}</h5>
</div>

<hr>
<div class="text_field">
    {{ Insight.description|safe }}
    <a href="{{ Insight.url }}">Link to Wikipedia</a>
</div>
{% endblock %}